extends: standard
plugins:
  - standard
  - promise

env:
  jquery: true
  browser: true
  node: true


rules:
   quotes: [2, "double", { "avoidEscape": true, "allowTemplateLiterals": true }]
   semi: [2,"always"]
   no-multi-spaces: [2,{"exceptions": { "VariableDeclarator": true }}]
   no-multiple-empty-lines: 0
   space-before-function-paren: 0
   no-multi-str: 0
   new-cap: [2,{ "newIsCapExceptions": ["moment"] ,capIsNewExceptions:["True","Router","False"] }]
   no-useless-escape: 0

parserOptions:
  ecmaVersion: 2018
